#!/bin/bash
#This is my 1st shell script to print output
echo "Hello All, Welcome to AWS/Devops Class"
echo "Hello, How are you?"
echo "Welcome to Young Minds"
echo "Hello batch-21, We are learning Jenkins"
echo "hello Team, How are you?"
echo "hello we are learing devOps this is get session"
echo "hello omkar your are learn Aws DevOps For job purpose"
echo "rahul how are you"
echo "today we have get session"
echo "i have done practice with git"
echo "we4 push the code into main branch"
echo "today we push our code into new branch"
echo "today we push our code into new branch"
echo "we learn Devops and complete AWS topic"
echo "we add new inc005"
echo "we getting"